### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by amymcgowan** [andreamartz/Email-Newsletter#11]
We should probably add a README for the project.  I'm thinking including something explaining the project, that each of us worked on it, what we each have done, that the project is for MCC, objectives of the project, what we've learned... + other things?

**Comment by andreamartz** [comment]
Wendy has an awesome looking README template on her Github account that she forked from someone else.  I forked it from her, and was going to try to explore using that (or at least the parts that are applicable to our project).  If you check out the template, let me know what you think.

**Comment by ghost** [comment]
All set!
