### ISSUE TITLE
Load images and icons

### ISSUE THREAD

**Issue by andreamartz** [andreamartz/Email-Newsletter#2]
# Load images and icons

Amy did a great job with finding and editing the images and icons.  Now we need to load them to the repo.

**Comment by andreamartz** [comment]
I created this issue just for the sake of creating my first issue. Hopefully this is the kind of thing issues are used for.

**Comment by amymcgowan** [comment]
Great! I'll take a look at it tomorrow morning. I know you were really
hoping to get the images tonight. I'm really sorry I didn't get to it. The
class has taken up all of my time lately, so I took most of the night off
for my and family's sake. I'll try to figure out how to load the images
first thing in the morning so you'll be able to play with them then.
Looking forward to tomorrow!

**Comment by andreamartz** [comment]
Not a problem at all!  I'm keeping busy, believe me.  I think we are running ahead of schedule anyway.  Time will tell, but it looks that way to me right now.  Sleep well.  I'll talk with you tomorrow morning.

**Comment by amymcgowan** [comment]
Thank you for understanding :)

**Comment by amymcgowan** [comment]
Files uploaded
