### ISSUE TITLE
Images are on both master and html-and-css branches

### ISSUE THREAD

**Issue by andreamartz** [andreamartz/Email-Newsletter#3]
I did not intentionally duplicate these onto the html-and-css branch.  Can they be deleted?

**Comment by andreamartz** [comment]
I tried to remove the html-and-css branch at the command line.  It's not working.

**Comment by amymcgowan** [comment]
Are they actually duplicates or are they just available to you on the other branch?  I think anytime you make a branch off of master, you still have access to any other files/assets that are on master

**Comment by amymcgowan** [comment]
On a related note, I actually think we would be fine to remove the images from the repo.  Since we are using the urls of the hosted images, it's probably not necessary to have them here.  ??

**Comment by amymcgowan** [comment]
If it's okay with you, I can just remove the images from the repo entirely.

**Comment by andreamartz** [comment]
I managed to do it on the two branches before I saw your replies here (glad you agree that we can get rid of them).  They are still in the folder on master.  I guess I don't fully understand how folders/directories work in GitHub, because I can't seem to access that folder's contents.
Anyway, I'll leave this issue open in case you wanted to also remove that folder from master.

**Comment by amymcgowan** [comment]
Removed img folder
